@startuml UseCase
left to right direction

actor "User" as U

rectangle "Authentication" {
    usecase "Login" as UC1
    usecase "Logout" as UC2
    usecase "Register" as UC3
}

rectangle "Message Handling" {
    usecase "Send Message" as UC4
    usecase "Receive Message" as UC5
}

rectangle "Chat History" {
    usecase "Save Chat History" as UC6
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6

@enduml
